account/urls.py
from .views import (
    UserProfileView, CustomLoginView, RegisterView, VerifyCodeView, CompleteProfileView, EditProfileView,
    CustomChangePasswordView, MyBooksView, WishlistView, RemoveFromWishlistView
)
from django.urls import path
from django.contrib.auth import views
app_name = 'account'
urlpatterns = [
    # path(
    #     "password_change/done/",
    #     views.PasswordChangeDoneView.as_view(),
    #     name="password_change_done",
    # ),
    # path("password_reset/", views.PasswordResetView.as_view(), name="password_reset"),
    # path(
    #     "password_reset/done/",
    #     views.PasswordResetDoneView.as_view(),
    #     name="password_reset_done",
    # ),
    # path(
    #     "reset/<uidb64>/<token>/",
    #     views.PasswordResetConfirmView.as_view(),
    #     name="password_reset_confirm",
    # ),
    # path(
    #     "reset/done/",
    #     views.PasswordResetCompleteView.as_view(),
    #     name="password_reset_complete",
    # ),
]

urlpatterns += [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("verify/", VerifyCodeView.as_view(), name="verify_code"),
    path("profile/", UserProfileView.as_view(), name="profile"),
    path('profile/complete/', CompleteProfileView.as_view(), name='complete_profile'),
    path("profile/<int:pk>/edit/", EditProfileView.as_view(), name="edit_profile"),
    path("password_change/", CustomChangePasswordView.as_view(), name="password_change"),
    path("books/", MyBooksView.as_view(), name="books"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path('book/<int:pk>/remove_from_wishlist/', RemoveFromWishlistView.as_view(), name='remove_from_wishlist'),
]

adminpanel/urls.py
from django.urls import path
from adminpanel.views import DashboardView, BookListView, CreateBookView, ReturnBookView, CategoryListView, \
    CreateCategoryView, LoanListView, CreateLoanView, DeleteBookView, ListAuthorView, CreateAuthorView, \
    DeleteAuthorView, DeleteCategoryView, UpdateAuthorView, UpdateCategoryView, BookUpdateView, CommentListView, \
    CommentDetailView, ApproveCommentView, DeleteCommentView

app_name = 'adminpanel'

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("book/", BookListView.as_view(), name="book_list"),
    path("book/add/", CreateBookView.as_view(), name="add_book"),
    path("book/<int:pk>/return/", ReturnBookView.as_view(), name="return_book"),
    path("book/<int:pk>/delete/", DeleteBookView.as_view(), name="delete_book"),
    path("book/<int:pk>/update/", BookUpdateView.as_view(), name="update_book"),
    path("category/", CategoryListView.as_view(), name="category_list"),
    path("category/add/", CreateCategoryView.as_view(), name="add_category"),
    path("category/<int:pk>/delete/", DeleteCategoryView.as_view(), name="delete_category"),
    path("category/<int:pk>/update/", UpdateCategoryView.as_view(), name="update_category"),
    path("loan/", LoanListView.as_view(), name="loan_list"),
    path("loan/add/", CreateLoanView.as_view(), name="add_loan"),
    path('author/', ListAuthorView.as_view(), name='author_list'),
    path('author/add/', CreateAuthorView.as_view(), name='add_author'),
    path('author/<int:pk>/delete/', DeleteAuthorView.as_view(), name='delete_author'),
    path('author/<int:pk>/update/', UpdateAuthorView.as_view(), name='update_author'),
    path('comment/', CommentListView.as_view(), name='comment_list'),
    path('comment/<int:pk>/detail/', CommentDetailView.as_view(), name='comment_detail'),
    path('comment/<int:pk>/approve/', ApproveCommentView.as_view(), name='approve_comment'),
    path('comment/<int:pk>/delete/', DeleteCommentView.as_view(), name='delete_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('account/', include('account.urls')),
    path('adminpanel/',include('adminpanel.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [
    path('', views.MainPageView.as_view(), name='main_page'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_info'),
    path('book/<int:pk>/add_to_whishlist', views.AddToWishListView.as_view(), name='add_to_wishlist'),
    path('category/<int:pk>/', views.BooksInCategoryView.as_view(), name='books_by_category'),
]

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/forms.py
from django import forms
from django.db.models import Q

from library.models import Loan, Book

class CreateLoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['member', 'book']

    def __init__(self, *args, **kwargs):
        super(CreateLoanForm, self).__init__(*args, **kwargs)
        self.fields['book'].queryset = Book.objects.filter(~Q(loan__status__in =['b','o']))

adminpanel/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db.models import Count, Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.timezone import now, timedelta
from django.views import View
from django.views.generic import UpdateView, CreateView, ListView, TemplateView, DeleteView, DetailView
from adminpanel.forms import CreateLoanForm
from adminpanel.mixins import StaffRequiredMixin
from library.models import Loan, Category, Book, Author, Comment

User = get_user_model()

class DashboardView(LoginRequiredMixin, StaffRequiredMixin, TemplateView):
    template_name = 'adminpanel/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['book_count'] = Book.objects.count()
        context['members_count'] = User.objects.filter(is_active=True).count()
        context['category_count'] = Category.objects.count()

        context['recent_users'] = User.objects.order_by('-date_joined')[:5]

        context['recent_comments'] = Comment.objects.select_related('user').order_by('-created_at')[:5]

        today = now().date()
        days = [(today - timedelta(days=i)) for i in reversed(range(7))]
        registration_counts = []
        for day in days:
            count = User.objects.filter(date_joined__date=day).count()
            registration_counts.append(count)

        context['registration_days'] = [day.strftime('%d/%m') for day in days]
        context['registration_data'] = registration_counts

        return context



class CommentListView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = Comment
    template_name = 'adminpanel/comment_list.html'

    def get_queryset(self):
        return Comment.objects.select_related('user','book').filter(is_approved=False)


class CommentDetailView(LoginRequiredMixin, StaffRequiredMixin, DetailView):
    model = Comment
    template_name = 'adminpanel/comment_detail.html'
    context_object_name = 'comment'

    def get_queryset(self):
        return Comment.objects.select_related('user','book').filter(is_approved=False)


class ApproveCommentView(LoginRequiredMixin, StaffRequiredMixin, View):
    def post(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        comment.is_approved = True
        comment.save()
        return redirect('adminpanel:comment_list')


class DeleteCommentView(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
    model = Comment
    template_name = 'adminpanel/comment_confirm_delete.html'
    success_url = reverse_lazy('adminpanel:comment_list')


class CreateBookView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'short_description', 'full_description', 'author', 'category', 'image']
    template_name = 'adminpanel/book_form.html'
    success_url = reverse_lazy('adminpanel:book_list')


class DeleteBookView(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
    model = Book
    template_name = 'adminpanel/book_confirm_delete.html'
    success_url = reverse_lazy('adminpanel:book_list')


class BookListView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = Book
    template_name = 'adminpanel/book_list.html'

    def get_queryset(self):
        queryset = Book.objects.select_related('author').order_by('-placed_at')
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(author__name__icontains=query) |
                Q(category__title__icontains=query)
            )
        return queryset


class BookUpdateView(LoginRequiredMixin, StaffRequiredMixin, UpdateView):
    model = Book
    template_name = 'adminpanel/update_book.html'
    fields = ['title', 'short_description', 'full_description', 'author', 'category', 'image']
    success_url = reverse_lazy('adminpanel:book_list')


class CreateCategoryView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    model = Category
    template_name = 'adminpanel/category_form.html'
    fields = ['title', 'image']
    success_url = reverse_lazy('adminpanel:category_list')


class CategoryListView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = Category
    template_name = 'adminpanel/category_list.html'
    def get_queryset(self):
        return Category.objects.annotate(books_num = Count('book'))


class DeleteCategoryView(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
    model = Category
    template_name = 'adminpanel/category_confirm_delete.html'
    success_url =  reverse_lazy('adminpanel:category_list')


class UpdateCategoryView(LoginRequiredMixin, StaffRequiredMixin, UpdateView):
    model = Category
    template_name = 'adminpanel/update_category.html'
    fields = ['title', 'image']
    success_url = reverse_lazy('adminpanel:category_list')


class LoanListView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = Loan
    template_name = 'adminpanel/loan_list.html'

    def get_queryset(self):
        queryset = Loan.objects.order_by("-borrowed_on")
        query = self.request.GET.get('q')

        if query:
            queryset = queryset.filter(
                Q(book__title__icontains=query) |
                Q(member__first_name__icontains=query) |
                Q(member__last_name__icontains=query)
            )


        return queryset


class CreateLoanView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    form_class = CreateLoanForm
    template_name = 'adminpanel/loan_form.html'
    success_url = reverse_lazy('adminpanel:loan_list')

    def form_valid(self, form):
        member = form.cleaned_data['member']

        active_loans = Loan.objects.filter(
            member=member,
            status__in=['o' , 'b']
        ).count()

        if active_loans >= 2:
            form.add_error(None,"این عضو در حال حاضر دو کتاب قرض گرفته است. نمیتوان بیشتر از دو کتاب قرض گرفت")
            return self.form_invalid(form)

        messages.success(self.request, "کتاب با موفقیت قرض داده شد.")
        return super().form_valid(form)


class ReturnBookView(LoginRequiredMixin, StaffRequiredMixin, UpdateView):
    model = Loan
    template_name = 'adminpanel/return_book.html'
    fields = []

    def form_valid(self, form):
        loan = form.instance
        loan.status = 'r'
        loan.save()
        messages.success(self.request, "کتاب با موفقیت برگردانده شد")
        return redirect('adminpanel:loan_list')


class CreateAuthorView(LoginRequiredMixin, StaffRequiredMixin, CreateView):
    model = Author
    template_name = 'adminpanel/author_form.html'
    success_url = reverse_lazy('adminpanel:author_list')
    fields = ['name', 'bio']


class ListAuthorView(LoginRequiredMixin, StaffRequiredMixin, ListView):
    model = Author
    template_name = 'adminpanel/author_list.html'

class DeleteAuthorView(LoginRequiredMixin, StaffRequiredMixin, DeleteView):
    model = Author
    template_name = 'adminpanel/author_confirm_delete.html'
    success_url =  reverse_lazy('adminpanel:author_list')


class UpdateAuthorView(LoginRequiredMixin, StaffRequiredMixin, UpdateView):
    model = Author
    template_name = 'adminpanel/update_author.html'
    fields = ['name', 'bio']
    success_url = reverse_lazy("adminpanel:author_list")

templates/adminpanel/author_confirm_delete.html
<!doctype html>
{% load static %}
<html lang="en" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'account/img/fav.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.12.1/css/pro.min.css">
  <link rel="stylesheet" type="text/css" href='{% static "account/css/style.css" %}'>
  <title>صفحه مدیریت</title>
</head>
<body class="bg-gray-200">


{% include './navbar.html' %}

<div class="h-screen flex flex-row flex-wrap">

  {% include "./sidebar.html" %}

  <div class="flex-1 flex justify-center items-center mb-84">
    <div class="bg-white p-8 rounded-lg shadow-md">
      <h2 class="text-lg font-semibold mb-4">آیا از حذف کردن نویسنده مطمئن هستید؟</h2>

      <form method="post" class="flex ">
        {% csrf_token %}
        <button type="submit" class="bg-green-500 text-white px-4 rounded-lg w-1/2">
          حذف
        </button>
       <a href="{% url 'adminpanel:author_list' %}" class="block mr-2 px-4 py-2 bg-red-500 rounded-lg w-1/2 text-center text-white">انصراف</a>
      </form>
    </div>
  </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src={% static "account/js/scripts.js" %}></script>

</body>
</html>

templates/adminpanel/author_list.html
<!doctype html>
{% load static %}
<html lang="en" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
  <link rel="shortcut icon" href="{% static 'account/img/fav.png' %}" type="image/x-icon">  
  <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.12.1/css/pro.min.css">
  <link rel="stylesheet" type="text/css" href='{% static "account/css/style.css" %}'>  
  <title>صفحه مدیریت</title>
</head>
<body class="bg-gray-200">

{% include './navbar.html' %}

<div class="h-screen flex flex-row flex-wrap" >

    {% include "./sidebar.html" %}

    <div class="bg-gray-100 flex-1 p-6">
        <div class="card h-full">
            <div class="card-body h-full">
                <div class="flex justify-between">
                    <h2 class="font-bold text-lg mb-10">نویسنده ها</h2>
                    <a href="{% url 'adminpanel:add_author' %}" class="btn h-10">افزودن نویسنده</a>
                </div>
                <table class="w-full border border-gray-300 rounded-lg overflow-hidden shadow-lg">
                    <thead class="bg-gray-100 text-gray-700 text-sm w-full">
                        <tr class="border-b border-gray-300">
                            <th class="py-3 px-4 font-semibold text-right">نام</th>
                            <th class="py-3 px-4 font-semibold text-right">بیوگرافی</th>
                            <th class="py-3 px-4 font-semibold text-right"></th>
                        </tr>
                    </thead>
                    <tbody class="text-gray-700 text-sm divide-y divide-gray-300">
                        {% for author in object_list %}
                        <tr class="hover:bg-gray-50 transition duration-200">
                            <td class="py-3 px-4 text-right">{{ author.name }}</td>
                            <td class="py-3 px-4 text-right">{{ author.bio }}</td>
                            <td class="py-3 px-4 text-right">
                            <a href="{% url 'adminpanel:delete_author' author.id %}" class="bg-red-500 text-white px-4 py-2 rounded-lg ml-2">
                      حذف        
                            </a>
                            <a href="{% url 'adminpanel:update_author' author.id %}" class="bg-blue-500 text-white px-4 py-2 rounded-lg">
                      ویرایش        
                            </a>
                            </td>
                            {% empty %}
                            <td class="py-3 px-4 text-center align-middle text-black -500 font-medium" colspan="7">هنوز نویسنده ای وجود ندارد</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- script -->
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src={% static "account/js/scripts.js" %}></script>
<!-- end script -->

</body>
</html>

templates/adminpanel/book_confirm_delete.html
<!doctype html>
{% load static %}
<html lang="en" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'account/img/fav.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.12.1/css/pro.min.css">
  <link rel="stylesheet" type="text/css" href='{% static "account/css/style.css" %}'>
  <title>صفحه مدیریت</title>
</head>
<body class="bg-gray-200">


{% include './navbar.html' %}

<div class="h-screen flex flex-row flex-wrap">

  {% include "./sidebar.html" %}

  <div class="flex-1 flex justify-center items-center mb-84">
    <div class="bg-white p-8 rounded-lg shadow-md">
      <h2 class="text-lg font-semibold mb-4">آیا از حذف کردن کتاب مطمئن هستید؟</h2>

      <form method="post" class="flex ">
        {% csrf_token %}
        <button type="submit" class="bg-green-500 text-white px-4 rounded-lg w-1/2">
          حذف
        </button>
       <a href="{% url 'adminpanel:book_list' %}" class="block mr-2 px-4 py-2 bg-red-500 rounded-lg w-1/2 text-center text-white">انصراف</a>
      </form>
    </div>
  </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src={% static "account/js/scripts.js" %}></script>

</body>
</html>

templates/adminpanel/dashboard.html
<!doctype html>
{% load static %}
<html lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="{% static 'account/img/fav.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.12.1/css/pro.min.css">
  <link rel="stylesheet" type="text/css" href='{% static "account/css/style.css" %}'>
  <title>صفحه مدیریت</title>
</head>
<body class="bg-gray-200">

<!-- start navbar -->
{% include './navbar.html' %}
<!-- end navbar -->

<div class="h-screen flex flex-row flex-wrap">

    <!-- start sidebar -->
    {% include "./sidebar.html" %}
    <!-- end sidebar -->

    <!-- start content -->
    <div class="bg-gray-100 flex-1 p-6 space-y-6">
        <div class="bg-white p-6 rounded-xl shadow mb-8">
            <div class="flex flex-col md:flex-row items-center">
                {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}" alt="" class="w-24 h-24 rounded-full mb-4 md:mb-0 md:mr-6">
                {% else %}
                <img src="{% static 'account/img/user.svg' %}" alt="" class="w-24 h-24 rounded-full mb-4 md:mb-0 md:mr-6">
                {% endif %}
                <div>
                    <h2 class="text-xl font-semibold text-center mb-2">{{ user.username }}</h2>
                    <p class="text-gray-500">{{ user.email }}</p>
                </div>
            </div>
        </div>
        <!-- آمار کلی -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div class="report-card">
                <div class="card">
                    <div class="card-body flex flex-col">
                        <div class="flex justify-end items-center">
                            <div class="h5 text-green-600 fad fa-book"></div>
                        </div>
                        <div class="mt-8">
                            <h1 class="h5">{{ book_count }}</h1>
                            <p>کتاب</p>
                        </div>
                    </div>
                </div>
                <div class="footer bg-white p-1 mx-4 border-t"></div>
            </div>

            <div class="report-card">
                <div class="card">
                    <div class="card-body flex flex-col">
                        <div class="flex justify-end items-center">
                            <div class="h5 text-yellow-600 fad fa-users"></div>
                        </div>
                        <div class="mt-8">
                            <h1 class="h5">{{ members_count }}</h1>
                            <p>عضو</p>
                        </div>
                    </div>
                </div>
                <div class="footer bg-white p-1 mx-4 border-t"></div>
            </div>

            <div class="report-card">
                <div class="card">
                    <div class="card-body flex flex-col">
                        <div class="flex justify-end">
                            <div class="h5 text-purple-600 fad fa-list"></div>
                        </div>
                        <div class="mt-8">
                            <h1 class="h5">{{ category_count }}</h1>
                            <p>دسته بندی</p>
                        </div>
                    </div>
                </div>
                <div class="footer bg-white p-1 mx-4 border-t"></div>
            </div>
        </div>

        <!-- دکمه‌های سریع -->
        <div class="flex flex-wrap gap-4 justify-center">
            <a href="{% url 'adminpanel:add_book' %}" class="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-lg">
                افزودن کتاب جدید
            </a>
            <a href="{% url 'adminpanel:add_author' %}" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-lg">
                افزودن نویسنده جدید
            </a>
            <a href="{% url 'adminpanel:add_category' %}" class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded-lg">
                افزودن دسته بندی جدید
            </a>
        </div>

        <!-- آخرین فعالیت ها -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">

            <div class="bg-white p-6 rounded-lg shadow-md">
                <h2 class="text-xl font-bold mb-4">آخرین کاربران ثبت شده</h2>
                <ul class="space-y-2">
                    {% for user in recent_users %}
                        <li class="flex justify-between text-gray-700">
                            <span>{{ user.first_name }} {{ user.last_name }}</span>
                            <span class="text-xs">{{ user.jdate_joined }}</span>
                        </li>
                    {% empty %}
                        <li class="text-gray-400">کاربری ثبت نشده.</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="bg-white p-6 rounded-lg shadow-md">
                <h2 class="text-xl font-bold mb-4">آخرین نظرات ارسال شده</h2>
                <ul class="space-y-2">
                    {% for comment in recent_comments %}
                        <li class="flex justify-between text-gray-700">
                            <span>{{ comment.user.first_name }}: {{ comment.text|truncatewords:5 }}</span>
                            <span class="text-xs">{{ comment.jcreated_at }}</span>
                        </li>
                    {% empty %}
                        <li class="text-gray-400">نظری ارسال نشده.</li>
                    {% endfor %}
                </ul>
            </div>

        </div>

        <!-- چارت ثبت‌نام کاربران -->
        <div class="bg-white mt-6 p-6 rounded-lg shadow-md">
            <h2 class="text-xl font-bold mb-6 text-center">ثبت نام کاربران در هفته گذشته</h2>
            <div id="registrationChart"></div>
        </div>

    </div>
    <!-- end content -->

</div>
<!-- end wrapper -->


<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script src={% static "account/js/scripts.js" %}></script>

<!-- اسکریپت چارت -->
<script>
document.addEventListener('DOMContentLoaded', function () {
    var options = {
        chart: {
            type: 'line',
            height: 300,
            toolbar: { show: false }
        },
        series: [{
            name: 'ثبت نام',
            data: {{ registration_data|safe }}
        }],
        xaxis: {
            categories: {{ registration_days|safe }}
        },
        colors: ['#10B981'],
        stroke: {
            curve: 'smooth'
        }
    };

    var chart = new ApexCharts(document.querySelector("#registrationChart"), options);
    chart.render();
});
</script>

</body>
</html>

templates/adminpanel/navbar.html
{% load static %}
<!-- start navbar -->
<div class="md:fixed md:w-full md:top-0 md:z-20 flex flex-row flex-wrap items-center bg-white p-6 border-b border-gray-300">

    <!-- logo -->
    <div class="flex-none w-56 flex flex-row items-center">
      <div class="user_section" style="  display: flex;align-items: center;gap: 1rem;padding-right: 0.5rem;">
            <a class="status-connection" style="width: 142px;background-color: #edfdfa;padding: 0.4rem;border-radius: 3px;text-align: center;color: #1f927f;"
               href="{% url 'adminpanel:dashboard' %}">کتابدار</a>
          </div>
    </div>
    <!-- end logo -->

    <!-- navbar content toggle -->
    <button id="navbarToggle" class="hidden md:block md:fixed right-0 mr-6">
      <i class="fas fa-chevron-double-down"></i>
    </button>
    <!-- end navbar content toggle -->

    <!-- navbar content -->
    <div id="navbar" class="animated md:hidden md:fixed md:top-0 md:w-full md:left-0 md:mt-16 md:border-t md:border-b md:border-gray-200 md:p-10 md:bg-white flex-1 pl-3 flex flex-row flex-wrap justify-between items-center md:flex-col md:items-center">

            <!-- right -->
            <div class="flex flex-row-reverse items-center">

              <!-- user -->
              <div class="dropdown relative md:static margin">
                <button class="flex items-center gap-2 text-sm text-gray-800 font-semibold focus:outline-none">
                  <span>{{ user }}</span>
                  <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M19 9l-7 7-7-7" />
                  </svg>
                </button>

                <button class="hidden fixed top-0 left-0 z-10 w-full h-full menu-overflow"></button>

                <div class="text-gray-500 menu hidden md:mt-10 md:w-full rounded bg-white shadow-md absolute z-20 right-0 w-40 mt-5 py-2 animated faster">

                  <form method="post" action="{% url 'account:logout' %}">
                      {% csrf_token %}
                      <button type="submit" class="px-4 py-2 block capitalize font-medium text-sm tracking-wide bg-white hover:bg-gray-200 hover:text-gray-900 transition-all duration-300 ease-in-out">
                        <i class="fad fa-user-times text-xs mr-1"></i>
                        خروج
                      </button>
                  </form>
                  <!-- end item -->
                  </div>
              </div>
              <!-- end user -->
              <i class="fas fa-user ml-3 text-2xl"></i>


            </div>
            <!-- end right -->

      <!-- left -->
      <div class="text-black-600 md:w-full md:flex md:flex-row md:justify-evenly md:pb-10 md:mb-10 md:border-b md:border-gray-200 btn-bs-dark">
        <a href="{% url 'library:main_page' %}" >نمایش سایت</a>
      </div>
      <!-- end left -->


    </div>
    <!-- end navbar content -->

  </div>
<!-- end navbar -->